// MB Myth Omens — extracted from Mythic Bastionland rulebook
// Keyed by myth name (matches MBRealmData.MYTHS)
export const MB_MYTH_OMENS = {
  'The Plague': [
    'An old coot proclaims their dreams, where foul air was choking people in their sleep. Pleads for help spreading the word.',
    'Moaning in the mist. An ivy-cloaked shack, home to a dying old couple. Their daughter left to search for treatment.',
    'Jolly hunter and his son with mild symptoms, chasing a smiling fox up a tree. They don\'t believe in the Plague, but claim the fox is a harbinger of death. The smiling fox wants to witness a death.',
    'A self-important Knight and two Squires, returning to report the Plague to the Seat of Power. Demands escort from other Knights. They carry a grey lantern, its light only visible to the carrier.',
    'A clearing, bonfire embers. An infected crowd, close to death, full of anger. They swear a blood oath on the stump of a red oak, seeing visions of revenge. They attack any caught watching.',
    'An infected village, the root of the Plague. All are visibly infected. Two Purging Knights, charging to cleanse with flame.',
  ],
  'The Wall': [
    'Crumbling outpost. A band of labourers sharing a meal on their way to begin work repairing the Wall. They think Knights are being sent to stop them.',
    'Two giant magpies, stealing shiny things. They nest in the trees that root among the Wall\'s oldest stones.',
    'Lonesome Wall Knight sat among colossal tree roots. She\'s strayed from the Wall, bored, in search of a little company.',
    'Pair of wardens, stuck at the bottom of a muddy slope. They search for a bandit who climbed the Wall. One is paranoid, eating from a pot of moonlit honey known to protect against illusions.',
    'A pair of furious refugees, heading to break the wall after being driven out of their home. They drank oil from the hidden giant\'s well, granting a terrible strength. They don\'t trust Knights.',
    'A distant army lies beyond the wall. A mercenary Warband heads to break an opening for them.',
  ],
  'The Shadow': [
    'Huge flatstones marbled with moss. Weeping winds. Tears from the skies, trees, some forming on your cheek.',
    'Ornate well, now stagnant. Sorrowful Knight, inconsolable, lashing at anyone who doesn\'t give him sympathy.',
    'Idealistic young alchemist collecting wind-tears found in the weeping winds. Tries to invoke sadness in all he meets.',
    'A strange nasal-toned flute, left with scraps of cloth. Playing stimulates sudden grief. Lose d6 SPI, dream of the Shadow.',
    'The Shadow, still, by a drowning-lake. They torment trespassers with visions of past sorrows. The water whispers, answering one question on behalf of the dead each day. At morning, a herd of grey deer visit the lake to show their respects.',
    'The Company find themselves in the Shadow\'s world. Islands in the mist of time. The mourned past can be seen as clear as the now. None can die here, but all who leave lose d12 SPI. The Shadows are only appeased by displays of grief.',
  ],
  'The River': [
    'Six monks, appeasing the River with offerings of bread. Their apparent leader is annoyingly vivacious and optimistic about their work tending to the River.',
    'Lost fisherman washed up on the riverbank. A mighty newt is sniffing around the shaken man.',
    'A rocky outcropping, a lone dead tree at its peak. Three monks seek a blood offering for the River. They need an innocent animal or a sinful person.',
    'Pilgrims arguing with a Bridge Knight chasing a toll. The Knight knows one of the pilgrims has a coin from the City and will take it by force if necessary.',
    'The River bursts into a new stream. If travelling, the route is cut off. For the first few moments, water from the newborn stream can heal any ailment.',
    'A great flood as the River gives birth to a new lake. It claims the entire Hex and spreads to neighbouring Hexes tomorrow. A spawning of mighty newts bursts forth the next day.',
  ],
  'The Wyvern': [
    'Crowned stag, crawling, poisoned. Its antlers are known to burn scaled beasts.',
    'A burial mound surrounded by a low stone wall. Much of it has been dug up, petty treasures scattered. The Wyvern screeches in the distance.',
    'The bloated body of a poisoned Knight, adoring Squire weeping at their side.',
    'Two foul eggs laid among battle carrion. The air feels sour. The poisonous young hatch at dark, share a feast, then lurch in opposite directions. A serrated blade forged with pain (2d6) lies with the dead.',
    'The Wyvern soars low, seeking revenge for a failed attack on its nest. The attackers have already fled. It clutches one of their silver shields (d6, A1), blessed by the iron willow.',
    'Fearing for its nest, the Wyvern lands to fight. If the situation is hopeless it flies to a neighbouring Realm, plotting revenge.',
  ],
  'The Goblin': [
    'Weeping huntsman, cursing everyone. Looking for his lost bloodhound who tended to him during injury.',
    'A lost lad, full of stories. Claims a little old man called him into the woods.',
    'Oppressive branches, tripping roots. A cloaked old man calls out, lost. If alerted he cries out just before he is dragged into the ground, taken to the lost realm.',
    'The lost pets are running wild. If spotted they immediately run back toward the secret door to the lost realm. One drops a strange metallic bone, repellent to birds.',
    'A dark clearing. Any deals made here are bound by fate. The Goblin offers a trade. A valuable lost thing in return for a favour he can call in later.',
    'Suddenly dragged to the realm of lost things. Tunnels under piles of bric-a-brac. The Goblin gloats from atop his pile. Freedom is only granted for a binding favour, which the Goblin will enforce.',
  ],
  'The Forest': [
    'A Seer, beloved by her village, now trapped, inert in ironwood. Only the Fearmonger can break their binds.',
    'A winding path beneath blue songbirds. They sing so fiercely that some lie breathless on the ground. The winding path leads to a distant forest Hex.',
    'The mother tree. Six woodland guardians attack anybody who looks upon it. Foxes, wolves, and wildcats fight as one.',
    'The Fearmonger in horrific form, parts of owl, boar, and mouse. Lurking in the mist, they hurl a thorn spear (d10 hefty, cannot be taken from the Forest) before retreating to the branches.',
    'A circle of blackened tree stumps. Inside, metal weapons roar with burning heat unless dropped. Then come the three great guardians: stag, boar, and bear. The Fearmonger preys from within the mist.',
    'The Fearmonger shows their true, terrible form as live, writhing wood. If they cannot be subdued the Forest bursts forth into the rest of the Realm.',
  ],
  'The Child': [
    'Drunken worshippers of the Child, rejoicing that the first sign has arrived. Mistrustful of anybody that won\'t join in.',
    '3 Seeker Knights and their redmaw wolf, escorting a Seer in the hunt for the Child, who they believe to be the key to the City.',
    'Fog shrouded lake, no deeper than a foot throughout. A rogue Seeker Knight searches for the Child, who they believe must be sacrificed to an awful creature in order to put it to rest for good. You\'re either with them or against them.',
    'An abandoned shack, empty cradle. A snake fang rattle, known to repel the wicked dead. The Burning Mother cries out in the distance. Any who look upon her are attacked on sight.',
    'A silvery waterfall. Metal placed within is repaired. Distant cheering and crying as the second sign comes into effect.',
    'At last they are here. A cradle of mist, the Child within. d6 Seeker Knights are here to kill them, another d6 here to protect and take them back to their Realm.',
  ],
  'The Order': [
    'A forge carved into the rock. Blacksmiths complaining about the Order\'s mistreatment of them. They want justice.',
    'A Company of the Order, seizing supplies from local farmers. A frightened draft horse is bolting. The froth from its mouth causes a great frenzy if touched. A fight is about to break out.',
    'A dry clearing among boggy willow wood. The Order hold council, stood in a circle. Each must justify themselves to their peers, who can challenge any weakness. No spectators allowed.',
    'They are transporting a thief. The thief knows the burial place of a suit of silver plate (A1, immunity to weapons of inferior metal) and reveals this if freed.',
    'A Company rides on the trail of a monstrous beast. You\'re in their way.',
    'A Company leads an attack toward the nearest Holding. They have 3 Warbands alongside their retinue. They will lead the Realm into misrule or be driven beyond its borders.',
  ],
  'The Dead': [
    'Children playing "the skeleton gameâ€, wearing wooden skull-masks and throwing bones at passers-by.',
    'Terrified scout sisters, reporting wandering corpses on their patrol. Won\'t rest until taken seriously.',
    'Under Seer\'s orders, a graveyard is being burned as a precaution against the restless dead. Acolytes scatter dried herbs. Five great red vultures circle.',
    'A rotting corpse, mimicking its life as a forager. It is tethered to a nearby tree by a steel rope of impossible construction.',
    'Five skeletons, mocking bones, powered by hatred for the living, tormenting defenceless travellers. The travellers are artisans, known for their ability to make fine weapons out of certain woods.',
    '3 Warbands of rotting corpses and mocking bones, rising under a black banner, marching on the nearest Holding.',
  ],
  'The Underworld': [
    'A huge stone archway, former temple. Stars flicker in the shadows. White ravens caw from the trees. An opening appears in the arch, dark but light at once. Then all is normal again.',
    'Lost Knight from a distant place. She claims to have fallen through a shadow. A Shrouded Guide follows, seeking the toll.',
    'Narrow, twisted cave. Clanging within. A shrouded smith is forging a coldsword (2d8 hefty, ignores metal armour). It shatters if unsheathed in daylight.',
    'Heavy black cloth woven with indigo. If hung, opens to a place you want to be. Within, a dozen hands in the darkness require a toll of silver or blood. They will take either by force if needed.',
    'Broad, lilac-leaved trees. No artificial light can shine beneath. Five Shrouded Guides seeking to claim an owed toll.',
    'A creeping darkness, then suddenly within the Underworld. A dark reflection of our world. Without a Shrouded Guide the only exit is into a distant Realm.',
  ],
  'The Wurm': [
    'A leech-collector weeps. In a nearby swamp the colossal thing snatched her sister away with a bite. That bone- grinding noise haunts her.',
    'An argumentative sage complains. The balance of nature has been tipped. The birds aren\'t behaving correctly and there\'s not enough prey in the woods.',
    'A logging camp, crushed. Barrels of limeweed, a pungent appetite suppressor, left untouched. A Wurmshield surveys their master\'s work with unearned pride.',
    'A stinking grey salt-bog. Grinding laughter can be heard on the wind as the Wurm sleeps below, dreaming of the next feast. Two Wurmshields keep watch, arguing over who is more loyal.',
    'The Wurm lounges on smashed burial mounds of Seers. It speaks with four Wurmshields, loyal but poor company.',
    'The Wurm bursts from the ground, giving one opportunity for stimulating conversation before its great feast begins. It will not stop until bloated or dead.',
  ],
  'The Pack': [
    'Wailing shepherd. His sheepdogs have slaughtered their flock and fled. Crows feast on the gore. His family are hungry.',
    'A band of poets and scribes fight among themselves, unable to speak except snarling growls. The Pack watch from a nearby hill, scattering if disturbed. When they leave, the wanderers\' voices return.',
    'A rival fighting the leader. 6 wolves guard against interruption. They favour the challenger. The leader is toying with him and tears his throat when he gets bored.',
    'The wind suddenly stops, then the sound of jaws lapping at air. Then the howl, rough and screeching. Countless howls join the call, air completely still. Soon the howl stops and the wind returns.',
    'An important trade road has been blockaded by savagely torn trees and heaps of soil wet with blood.',
    'The 13 wolf pack howls in their den, setting their sights on a nearby Dwelling or Holding, attacking the humans and their broken beasts in dark or mist.',
  ],
  'The Eye': [
    'Nothing more than the hollow grunts of moon toads in the roots. When the Knights sleep they share a dream of a great eye sprouting from the ground.',
    'An elderly tanner has been banished from her home for sowing discord. She dreamt embarrassing truths about her neighbours and couldn\'t resist sharing.',
    'Grey birds watch from the branches. When scattered they flutter about in a spiralling circle before dispersing.',
    'Five acolytes march toward the nearest settlement. They aim to tear down walls so that all can be revealed to the Eye.',
    'A parade of dozens of acolytes, wheeling a wooden wagon carrying a boulder painted with a spiral eye. It is a peaceful parade, but they warn the ascent is coming.',
    'A rumbling below, then the Eye rises from the earth. Acolytes run to be near. It sprouts legs and begins to march toward the nearest Seer, aiming to devour them for their knowledge before returning to the earth.',
  ],
  'The Blade': [
    'A booming voice singing in the distance. A travelling cook belts out songs about the Blade\'s previous owners, each reaching a tragic end (see opposite).',
    'A cliff-side village, ruined long enough to be overgrown with moss and thorns. In a ruined chapel an altar is inscribed with: Forsake in earth, unbroke by time Afore first draw, that greedsome war',
    'Band of 5 cutthroats think the Knights have the Blade or know its whereabouts.',
    'Down a spiral of natural steps, a bloodied sharpening wheel screams on the wind. Can sharpen blades to a keen edge (+d8) but they break after their first Wound.',
    'A cave concealed by a steaming waterfall is the resting place of the Scabbard, which destroys any blade placed inside. The waterfall scalds (d10) anybody wielding a weapon, harmless to the unarmed.',
    'A louse-infested dead forest. The Blade lies within, but travellers are lured by visions of something they truly desire.',
  ],
  'The Legion': [
    'A field littered with martial detritus. Broken helms, shields, and bodies. The mud grabs at those passing over, groans on the wind. A lean horse is trying to pull its dead rider from the ground to no avail.',
    'A lone legionnaire deserter. Can only grunt in cowardice, scouring the land for a place to hide. A pack of 5 legionnaires are tracking them, minutes away.',
    'A local militia are camped, recovering from a clash with the Legion. Few are dead, but the wounded cry in agony. The lacerations of the Legion\'s barbed blades are as fresh as when they were cut.',
    'A Legion Warband on the horizon, firing their arrows at the farthest possible range. Break into retreat if approached.',
    'A new legionnaire pulling themselves from the earth. Pained, clutching rusted arms. Seeks the comfort of the Legion.',
    'Three Legion Warbands invade the nearest Holding. If defeated they return in greater ranks. The war only ends if they are driven into fire or water.',
  ],
  'The Imp': [
    'A trail, glittering dust on the surface. A moment later, a flash ignites five dancing white flames that torment the travellers. They vanish once they have caused pain.',
    'Smouldering heat can be felt from the shadows of looming trees. The darkness itself burns (d6 Damage) any within, but does not set things alight. The shadows return to normal after this Phase.',
    'A fluttering swarm of bats descend on the Knights. They are in the thrall of the Imp, flying to him after they have drawn blood.',
    'A feast is laid out on a grand table that shouldn\'t be here. If they partake he appears and plays some impish pranks. If they refuse he attacks with his black fire.',
    'The trail turns to a maze, smoke rolling in, soon surrounded by walls of flame. He releases the victims when they are adequately frustrated.',
    'He is holding court, arguing with eight foxes in their language. If their meeting is allowed to conclude he stomps away, banished by their words.',
  ],
  'The Troll': [
    'In an itchy marsh, a severed, rubbery arm pulls itself along. Claws at anybody that interferes. Has no sense of direction, eventually withering to dense, dead flesh.',
    'A tiny chameleon watches from a crooked branch. Hisses a warning if anybody passes near, stirring the Troll in the nearby trees, fleeing back to its home.',
    'A burglar is fleeing from an abandoned cave, a home carved into the earth. Clumsy furniture cobbled from rock and mud. Blood on the ground, smashed bones, another dead troll limb. The burglar found nothing of value in there.',
    'The Troll drags a dying warhorse back toward its new cave. A Knight lays dead.',
    'Bronze, shimmering pond amongst a bog of fly-infested reeds. Disturbing the water grants a vision of the Troll being attacked by soldiers with axes, hacking the creature to bits.',
    'Split from head to pelvis, the Troll holds itself together as it rampages, craving meat to aid the regeneration.',
  ],
  'The Demon': [
    'The bloody remains of an ivory goat, its innards laid out in a broad spiral. White goats are never eaten, thought to be reincarnations of Seers from the past.',
    'A singer, beating a drum. They sing cruel lyrics about the Knights, knowing more than they possibly could. They utterly ignore the Knights, even if apprehended.',
    'In a meadow, a band of drunks are feeding a bonfire, growing out of control. They openly praise the Writher Within, gloating that he\'s coming to eat the Seers and free us from their lies.',
    'The sun is black, gold light flooding from its corona. Animals panic, Seers are blinded. This lasts until the next sunrise.',
    'A once-beloved Knight now rampages through the Realm slaughtering serfs. Her head has sprouted a curved horn on one side, all humanity now gone.',
    'A bloated serf is being dragged away before bursting in a red mist. The Demon emerges from within in their true form, not resting until they have eaten 7 Seers.',
  ],
  'The Sea': [
    'On glittering rapids, a shepherd is being attacked by 8 wolfcrabs, usually only seen scavenging on beaches.',
    'Salty rain batters the land, web-like weed hanging from the trees. In an abandoned bowyery, deer and boars take shelter.',
    'At the site of a modest pond, a new sea rises forth, its tide surging out night and day. Roaring coots honk out in a deafening protest.',
    'The Two-Hearted Knight bellows at the Sea, trying to repel the water with their coral ring. They don\'t know that they must be submerged in the water to command it.',
    'A great storm begins, and won\'t stop until the wave has arrived. Saltwater rises from all water sources, the land is flooded, and harvest ruined.',
    'The wave swells on the horizon, as tall as a mountain range. If it washes over the Realm then little can survive. After the devastation the Sea is quelled and returns to its rightful place.',
  ],
  'The Elf': [
    'Along a sheltered stream, isolated signs of the next Season arriving early.',
    'Two season destroyers are about to kill a defenceless, defeated ironsmith outside his tiny forge. They claim the tide of seasons requires fresh blood.',
    'A season scout carries the rod of the upcoming Season, wishing to gift it to a Seer courtesy of the Elf. The rod holds the power to usher in its Season early.',
    'A season scout gifts the bow of the upcoming Season (d8 long) to the Knight with the highest SPI score. It is imbued with the power of the upcoming Season, when it is more potent (2d8).',
    'A season scout is travelling to the Seat of Power to deliver a message to the ruler of the Realm. They carry the longly viper, a leaping, talking snake. Only the viper knows the message, that the Elf is coming to claim this Realm as their own.',
    'The Elf emerges to claim the Seat of Power, a Warband each of scouts and destroyers. They\'d prefer a duel.',
  ],
  'The Axe': [
    'A cowherd sleeps on a branch. Then, a rumble in the ground followed by their cattle stampeding this way.',
    'A maze of stony crags. A message carved in the rock: "All Knights will feel the Axeâ€.',
    'A ruined hexagonal temple, seven stone seats the only furnishings left within. Each has a skull placed on it, the crest of a Knight roughly scratched into each seat. A flame weasel gnaws on one of the skulls.',
    'A secluded orchard, pained groans amongst the birdsong. A Knight lies bleeding, arm severed by the Axebearer. She doesn\'t know why she was spared.',
    'Echos of conversation from a winding tunnel. The militia within are discussing whether the Knights should lay down their lives to appease the Axebearer.',
    'The Axebearer stands atop a crag, proclaiming that the Axe will break the very land in two. Their first strike to the ground causes rumblings, the second tears a chasm across the Hex, the third a mighty canyon across the whole Realm.',
  ],
  'The Dwarf': [
    'An ancient fountain, smashed to pieces, tended to by a lone Dwarf. He uses his hammer to gently piece the stone back together. Claims to be in the service of the ruler of the Realm, happy to work again.',
    'Voices from within a shadowy grove. Mercenaries, arms freshly forged by the Dwarf, discussing where to find work.',
    'A sudden, broad tunnel entrance. The Dwarf leads reluctant labourers in digging out a passage to a distant Realm. He doesn\'t care where. The earth itself appears to bleed in the ground around the tunnel. The Dwarf seems undeterred.',
    'Suddenly rising from the ground, three great giants of vengeful earth lash out at any people they can find.',
    'Band of traders, labourers, and thieves from a distant Realm. Claim they arrived through the tunnel, looking for a home.',
    'The earth writhes and convulses. The ground opens up to claim the nearest Holding, swallowing it into the distant Realm at the end of the tunnel.',
  ],
  'The Tower': [
    'Marching across a barren moor, the Bolt Knight escorts labourers in carts. They are being taken to the site of the Tower, where more efforts are needed.',
    'A dozen great birds of burden haul huge blocks across the Realm. A wake of torn earth. Tower guards escort on horseback.',
    'A stairway in the wilds, dreamlike visions to any who ascend (see opposite). At the top, a clear view of the Tower, complete on the horizon.',
    'Black clouds and thunder, but no rain. Crackling lightning turns to bolts, sparking fires across the Realm. This does not end until the Tower falls.',
    'A titanic thunderclap and dazzling bolt of lightning. The Tower begins to fall and cannot be stopped. The thunder and lightning continue.',
    'With a swell of thunder all tower-like structures in the Realm are shaken, grand or humble. With a final clap they all fall. The clouds clear.',
  ],
  'The Chariot': [
    'The stars are visible, even in day, forming a wheel pattern, visibly turning.',
    'A huge crater, barely the rubble of a stone outpost left. Heavy footprints within.',
    'A distraught family claim a pair of great tigers attacked their small farm, eating their chickens, sheep, and dog. They claim the beasts fell from the sky and vanished back into the darkness.',
    'A swathe has been cut through a forest or mountain. It leads toward the Myth Hex.',
    'The Charioteer rides over the horizon, pulled by two great tigers. He is quick to share his past triumphs, gathering followers to feed his ego. He seeks revenge against the ruler of the nearest Holding, who has slighted him in a minor way.',
    'Following up on a boast that somebody doubted, the Charioteer is preparing to charge either upstream, or into the tide, proving that no mere water is a match for the Chariot. They will succeed at this, driving the water away for good, before taking flight and returning to the stars.',
  ],
  'The Desert': [
    'Winds bring a sudden dust storm. Visibility is short and travel impossible. It blows over by nightfall.',
    'Farmer staring into the clear sky. Claims the air feels too still. Until this Myth is resolved there is no rain, the land gradually dries out, rivers start to wither.',
    'Oily buzzards circle above, a band of hunters below are playing dead in an attempt to catch and eat them. These birds are usually only found in barren wastelands.',
    'A disembodied eye floats, watching the Knights. If touched it turns to dust. The hag has taken note of them.',
    'A parched stream, grey dusty earth flowing upstream toward the dust hag\'s rocky lair.',
    'In her lair, the dust hag unleashes the Desert in full. Every Hex within 3 Hexes of the Myth Hex is now the Desert as long as she lives.',
  ],
  'The Mountain': [
    'Fur-clad monks pray toward the Mountain, scattering stones, water, and coals in its direction. They warn that only the worthy can climb it.',
    'The Mountain appears on the horizon. A pack of 4 crag cats have descended, laying gems as bait for unsuspecting prey.',
    'The Mountain\'s shadow swells, covering the Realm most of each day. Animals are distressed, crops struggle in the gloom.',
    'Seven peacock riders approach the Mountain. They claim their peacocks are so magnificent that nature simply gives way to them. They are mistaken.',
    'Two Squires return from near the peak. Their Knights were killed by a pack of crag cats, the Squires killing the cats in revenge. They\'re headed to the nearest Holding to seek their knighthoods.',
    'Atop the mountain, a voice questions anybody at the peak. "Are you worthy?â€ Those who answer yes receive a brief vision of a glittering city. After leaving the Mountain it fades from the horizon.',
  ],
  'The Star': [
    'A green star appears in the sky, brighter than any other, slowly circling.',
    'An archer lies on a flat rock. Trails of pale light fall from the Star onto the Realm.',
    'Spires of dull metal, planted in the ground, forming a barrier, blocking travel in the direction of the Myth Hex. Moving toward the barrier causes intense pain, pushing through it causes d12 Damage, ignoring Armour and other protection.',
    'A silver spire, patrolled by a walking tower on birdlike legs. Smaller spires slowly grow around the central spire.',
    'A mass of twenty commoners being escorted by 3 walking towers. They are being taken to the Myth Hex to be fed into the red spire that grows there.',
    'Helpless commoners being forced into the opening at the base of a towering silver spire. 5 walking towers guard them. When they have all been taken on board the spire glows with a blinding light before returning to the green star with a screaming streak. The Star fades.',
  ],
  'The Sun': [
    'A field of golden flowers, moles-a-brightly munching on their stems. The Sun appears extra bright, even peeking over the horizon at night.',
    'A couple, vagabonds living off the land, carrying a basket of fruit. They praise the Sun for an unusually ripe bounty. Immediately flee from the Knights.',
    'The Sun rises to new heights, not setting again until the Myth is resolved. Roll a new blessing of the Sun each time you arrive at a settlement (see opposite).',
    'A shady grotto, 5 raiders arguing loudly within. They are frustrated that they cannot raid at night anymore. They plan a dire attack on the nearest Holding.',
    'A drought on the land. Wells dry, ground hardens, rivers die. The Sun brings no more boons, only banes.',
    'The Sun swells further, then descends on the Realm in the form of the feaster, a colossal golden man. He bounds about the Realm eating anything that grows. Terrified of animals, but not humans.',
  ],
  'The Moon': [
    'On a steep-sloped scrubland an elderly woman gathers thorns. She claims they ward off the Claw, who\'s due another victim any night now.',
    'The Moon looms as a sharp crescent. When night falls the Claw begins to screech from the darkness. It only strikes if it spots a vulnerable target.',
    'Ferocious revellers dance around a beast idol. They break animal and human bones against the stone totem, keeping the Bonebreaker at bay for another night.',
    'The Moon looms large and crooked. As soon as night falls the Bonebreaker strikes suddenly and without warning.',
    'A wild-haired sage tries to calm a panicking congregation. He laments that they have no reptiles to sacrifice, a tradition intended to ward off the Bloodsucker, so instead people should arm themselves and bar their doors.',
    'The Moon looms waning and pale. When night falls the Bloodsucker strikes when the Knights are most off-guard.',
  ],
  'The Lion': [
    'On the brink of a disused clay pit, a potter shapes a bowl, telling a story to the dozen children gathered to watch. She tells of the Lion, the king of beasts. No Knight could slay him, but a potter was his great enemy. She avoids giving any details.',
    'Horse breeders leading a dozen chargers toward the Seat of Power. They\'re struggling to get the horses moving, as they\'re all bowing toward the Lion\'s Hex.',
    'An isolated, babbling pond. A pike pokes its head from the water to cackle at passers-by. It can\'t really speak, but mimics words it has heard. It shouts "He\'s here for his crownâ€ among the gibberish.',
    'All steeds throw riders to the ground before charging off toward the Seat of Power to await the Lion\'s arrival.',
    'The Lion, heading toward the Seat of Power to peacefully take the Domain.',
    'Tired herald spreads word that the Lion has taken the Seat of Power. Some humans remain in court, but mostly they\'re replaced with unsuitable beasts.',
  ],
  'The Wheel': [
    'With a gust of groaning wind, the next Season begins suddenly.',
    'The wind groans again. At the start of the next morning a new Season begins, skipping next Season in line and moving immediately to the following Season. Birds screech and cry.',
    'The next Season begins suddenly. Milk finches are singing out of season, pushing their milk-filled eggs from their nests, breaking on the ground.',
    'The next Season is skipped, the following Season beginning suddenly. A grey adder, hisses from a nearby branch, beckoning the Knights over. It will whisper "the Wheel is brokenâ€ before biting anybody who lingers.',
    'An especially intense Winter arrives suddenly and will not end until the Wheel is repaired. Swirling clouds form above the Wheel\'s Hex, spinning at an irregular, stuttering pace.',
    'The Wheel vanishes. Now it can only be found in a distant Realm (see opposite).',
  ],
  'The Cudgel': [
    'A modest tower, a lone guard protecting a petty duchess. She is obsessed with sleep and dreams. The guard wants to seek the Cudgel, but needs somebody to watch the tower in his absence. Knows that a hawkleon lives nearby, and will be drawn to such a weapon.',
    'The corpse of a large white ox lies mauled but uneaten, twitching. Moments later a swarm of clawed bees bursts forth.',
    'A hawkleon prowls the shadows and circles the skies, hoping to make sport with the Knights if it can isolate one.',
    'A scheming hedgehog tracks the Knights, hoping to steal the Cudgel for itself.',
    'The cowardly guard believes they have the Cudgel. It\'s just a branch (d6 hefty).',
    'Finally, the true Cudgel (d10 hefty, the wielder knows the location of every enemy in their heart, but can never stop a fight until their enemy is dead), embedded in a huge slab of unbreakable green marble. Releases itself only for somebody who honestly intends to destroy it.',
  ],
  'The Lizard': [
    'Black smoke on the horizon. The Lizard is birthed from the fire, blind and confused. It cannot bite yet and tries to flee.',
    'A forest reduced to ash. A silver-haired bandit gathers it up. He knows that ash created by the Lizard is a deadly poison.',
    'A river, flowing as grey ash-saturated sludge. Dead fish and newts line the riverbank. A pair of knightly salamanders, normally immune to all toxins, flail around in agonised rage.',
    'A huge tail of the Lizard, detached by the growing beast, lies twitching amongst a briar patch. Its blood sparks a fire that can only be extinguished by seawater.',
    'A burial mound, where the Lizard made a temporary nest, erupts into burning soil and ash (d8 Damage each turn within the area). It burns until midnight.',
    'A heap of rocks, part melted, now the lair of the Lizard. If left to live it ignites into a huge fire that consumes the entire Hex, birthing four more Lizards to spread into neighbouring Realms.',
  ],
  'The Ogre': [
    'Snow begins to fall. First a flurry, then a veil that covers the whole Realm. Vision is limited to shouting distance. This remains until the Ogre dies or stops it.',
    'Two elderly weavers stagger through the snow. They were captives in the Ogre\'s castle. He released them because they would not work fast enough.',
    'The Ogre watches the Company from the veil of snow. He\'s looking for a Knight to capture, to guard his castle. Although he cannot die, he won\'t fight on long if hurt.',
    'Shivering in the snow, a stinging crocodile. It will lead Knights to the castle and a tunnel into the catacombs below.',
    'An ancient graveyard on a hilltop, names forgotten. Some know that the Ogre\'s soul is hidden in the first skull buried here.',
    'Having gathered enough servants to live a comfortable life, the Ogre bellows out in coarse laughter, heard across the Realm. His reluctant Knights gather taxes weekly, taking more than any can afford.',
  ],
  'The Spider': [
    'Six carrion storks pick at webbed corpses of a Knight, a Squire, and steeds.',
    'A makeshift trail suddenly gives way to a wide tunnel network. This labyrinth leads to the Myth Hex, but the Spider guards it.',
    'A skittering shadow in the clouds, then a blanket of thick webs covers the Company (VIG Save to break free). Next round, the Spider attacks, but only wants a snack.',
    'The Spider Herald watches over a gloomy mound, warning passers-by to keep their distance. The mound conceals a nest of writhing spider eggs. Any interference summons the Spider to defend his young.',
    'The Spider Herald arrives, beckoning the Company over. She inquires about their prowess, and if they seem worthy she cheerily informs them that they are now the Prey of the Spider, a great honour.',
    'The Spider bursts from the ground. He\'s been tracking the Company and fights until wounded, when he withdraws underground to return when fully healed.',
  ],
  'The Coven': [
    'The Cloud Hag descends from above, bombarding the Company with gusts of wind. She\'ll leave when she feels strong.',
    'A cauldron under a canopy of knotted trees. Anything dipped in glows with darkness. For the rest of the day the object is invisible to any that wish to harm you. If living matter touches the brew then one of the Coven bursts from within and admonishes for the intrusion.',
    'The Garden Witch stoops about in the shrubbery, plucking snails before eating them. She offers her snails, which allow the eater to speak with plants briefly.',
    'Amid a field of lush growth, a perfect circle of dead plants. Plants entering the circle wither and die. The Garden Witch has planted a saltstone causing this.',
    'The wind drops. The Achantrix screeches that there will be no night today. The next night phase is treated as day.',
    'The Coven fight to the death, nothing able to quell their hatred for each other. The victor mourns, then enters exile.',
  ],
  'The Lich': [
    'A grey wind shrieks into the Realm. Any items made of bone tremble for a moment.',
    'A ghost of shadow and smoke drifts nearby, clutching four gems. This is the ghost of the Lich, gathering his riches.',
    'A stream surges with blood toward the Myth Hex, a crumbled palace arisen.',
    'A hooded congregation surrounds an altar, a skull resting atop it. The Lich, as a skull, proclaims his return as the old king. If disturbed the hooded robes fall to the ground, no body within. The Lich threatens any Knights, but blasts off into the sky if he needs to retreat to his palace.',
    'The Lich, as a skull, rests on a heap of bones before reassembling to a human form, desiccated skin growing to cover his bones. Now with a full body he seeks to return to his palace and rule the Realm.',
    'A sky of skull-clouds bellow a new law each Season (see opposite). At Season\'s end, all who broke the law are struck by a black bolt (6d12 Damage, ignore Armour).',
  ],
  'The Wight': [
    'Beneath a grey willow, a young man washes a heap of clothes in a tiny pond. It\'s the cleanest water in the Realm. He sings a song about "a Knight that fought deathâ€ but forgets most of the words.',
    'The Wight rides forth on their ghostly steed. They shout a challenge to single combat, the loser allowing the winner to drive a sword through their heart. The Wight knows that this won\'t kill them.',
    'Creaking, gasping breath on the wind. The Wight hunches among a crown of jagged rocks. If disturbed they leap upon their steed and flee in shame.',
    'The Wight returns, another challenge of solo combat. Now the loser must allow the winner to burn them. The Wight tries to lose, but even fire does not kill them.',
    'An unmarked, recently dug grave. If disturbed the Wight bursts out and flees.',
    'A final challenge from the Wight, accompanied by a Seer. The Seer announces they will kill the winner in a horrible manner (see opposite).',
  ],
  'The Spectre': [
    'A funeral procession carries the Moth Knight, soon to be buried in home soil. She was a great Knight, but a poor ruler.',
    'A black hawk perches, then howls like a wolf before flying into the distance.',
    'An abandoned cabin, a clattering within. The Moth Knight cannot rest in shame. Her Spectre manifests, invisible and immaterial, throwing objects about inside the hut. After a moment the cabin itself is torn to shreds. Then nothing.',
    'In an instant the world appears as it will when all has turned to ruin. Everything is dead. As soon as a Knight touches something the world returns to normal.',
    'Three sages, close to death themselves, chant in a circle, pleading for the Spectre to rest, begging for her to leave shame behind. After a moment the Spectre lashes out at them, screaming wordlessly.',
    'The Spectre leads her ghostly horsemen. Her form is more solid now, and able to be physically harmed. She will be at rest only after a victory or a second death.',
  ],
  'The Wraith': [
    'A reedy song in the distance. A dark swan sings, advancing night or morning faster than normal. The swan flees if seen.',
    'Messengers carry word from all Seers. The Fallen Seer is to be killed on sight.',
    'In a dark patch of woods, a shadowy mass looms over a broken body. The shadow flees if seen. The corpse is a local Seer.',
    'A messenger from the nearest Seer calls for all Knights to report to guard them. The Wraith strikes on the next night.',
    'The Fallen Seer dances in the woods, cursing their brothers and sisters aloud. They spout false prophecies to Knights they meet (see opposite). At nightfall the Wraith attacks the Fallen Seer.',
    'The nearest Seer has come to seek the Wraith alone, offering themselves as sacrifice. The Wraith materialises at night and attacks. When this is done there is a scream heard across the Realm and the Wraith returns to wherever they were summoned from.',
  ],
  'The Beast': [
    'A hulking furred shadow moves between thick trees. Its form changes as you catch it at new angles (see opposite). It burrows into the ground if disturbed.',
    'A frightened rider points out two huge red eyes, watching on the horizon. Hot breath on your skin. The eyes close. Vanished.',
    'First a breath of wind, then a rumble, opening into a crackled roar. All animals in the Realm panic until the next sunrise.',
    'A clawed limb snatches at one of the Knights, emerging from the undergrowth, no body in sight. Each turn a new limb emerges to snatch at another Knight, up to six emerging in total. If the Knights flee the limbs retreat into earth.',
    'All Knights in the Realm that fail a SPI Save fly into rage, attacking all nearby. This ends if they are Wounded.',
    'With a howling bark the Beast bounds toward the nearest body of water. When it dives into the abyss a tidal wave covers all within two Hexes of the water, smashing buildings and flooding the land.',
  ],
  'The Judge': [
    'A wretch pleads for charity. She was a Knight, sentenced harshly by the Judge.',
    'A courtyard in black and white, carved seats in a circle. Vague voices echo, arguing, then a loud clap followed by silence. This place is gone if returned to.',
    'Three Sergeants of Law deliver a scroll to the Knight called for judgement. The Knight will be retrieved when the time is right; a horn will be the warning.',
    'One of the Knights vanishes into mist, forced to give witness to the trial of a Knight that they know. After testifying they are returned in a swirl of mist.',
    'A clear horn is heard across the Realm.',
    'The Retriever of Justice comes bounding on the horizon, roughly dragging the summoned Knight to court, which has materialised nearby. The Judge awaits, able to summon witnesses for or against, judging whether the Knight has truly done their best to follow the Oath. At the next sunset or sunrise she gives her verdict (see opposite).',
  ],
  'The Crown': [
    'An old herald from the Seat of Power rides, blasting his horn. He spreads word that the Seat of Power condemns the false Crown, and promises a vague reward for the one who turns it in for destruction.',
    'The same herald blasts their horn, announcing the hunt for the Crown. He has no memory of his previous message.',
    'Five brutal mercenaries approach, roughly interrogating any Knights to see what they know about the Crown, reporting back to the Seat of Power.',
    'The herald is beset by tiger spiders, d6 attacking openly, a further d6 lurking nearby waiting to pounce.',
    'Twelve brutal mercenaries are enforcing a curfew on all Knights, ordering them to return to the nearest Holding until the mercenaries have found and destroyed the Crown.',
    'In a well-lit clearing the Crown sits on a mahogany plinth.',
  ],
  'The Boar': [
    'The grass here feels like wiry bristles, the ground warm to the touch. Almost feels like the Realm is breathing heavily.',
    'Three hooded hunters are stalking the land, seeking the Boar who drove them out of their idyllic home nearby.',
    'A white-walled vineyard ahead. A sudden crash as the Boar arrives, tearing vines and crushing walls. It wants wine.',
    'If the hooded hunters are with the Company the Boar attacks, targeting the hunters specifically. Otherwise, their corpses lie broken in the Boar\'s wake',
    'Three masked hunters seek the Boar. They barely speak, miming as the animal on their mask. If their mask is ever removed they vanish into black smoke.',
    'The Boar in the distance, masked hunters concealed, ready to strike. If the Boar is killed the hunters unmask, vanishing to smoke. If the Boar survives it heads to the nearest holding for a final feast before leaving the Realm.',
  ],
  'The Eagle': [
    'A great shadow sweeps the landscape, blotting the sun for a moment.',
    'A flame above, shrieking until it plunges to the ground, sending roaring fire in every direction (d8 blast) and setting the area alight. The Eagle, Aflame, surveys the destruction then makes flight for the nearest large body of water.',
    'The Eagle, Smouldering, bathing to extinguish its feathers. It cannot fly for another Phase, but can hobble about. A crowd, driven from their burning homes, watch, and protect the Eagle from harm.',
    'The Eagle, Rising, stretches its wings, preparing to fly. As it ascends it sends a gust of wind through the Hex, felling wooden structures and flattening trees.',
    'The sun seems to swell, then a piercing cry. The shape of the Eagle, Aflame, appears in the sky, just circling for now.',
    'The Eagle, Aflame, dives on the Seat of Power, aiming to snatch the ruler and carry them up into the sun as an offering. If this fails the next harvest is dire.',
  ],
  'The Bat': [
    'A smug musician, drumming. He sings "the great winged one grows, and we are the feastâ€ but he insists it\'s just a song.',
    'A flock of various birds, grounded. They look to be grovelling toward the darkest part of the sky. They scatter if disturbed.',
    'A long table is laid out, commoners gathered for a feast. Every bowl is filled with worms, which people reluctantly eat by the handful. They say the Feast of Worms will deny the Bat its food.',
    'Exhausted farmers gather pigs, cows, and sheep. They\'re heading to a nearby lake for a great sacrifice, hoping the bloody water will sate the Bat\'s wicked hunger.',
    'A crowd are lighting fires outside a cave, the Bat hiding within. They aim to smoke it out. The Bat eventually emerges, and fights only enough to allow it to flee.',
    'Wings broken, dragged in chains, the Bat is being taken to the Seat of Power to be judged for its long list of crimes against the Realm (see opposite).',
  ],
  'The Toad': [
    'A caravan of wagons, fat donkeys hauling thick logs, escorted by twelve warty guards. They are respectful to Knights, but urge the need for haste, delivering materials for the Toad\'s castle.',
    'Two scouts, searching for news of the Toad. They hear his castle has been built.',
    'The Toad\'s pet, a monstrous slug, is being delivered to his castle in chains. Six warty guards struggle with the task, asking for help. The Toad is grateful for aid given.',
    'Nestled among thorns, a scroll with green ribbon. It reads "the Toad commends your serviceâ€. Anybody reading it feels sickly sweet, as if filled with honey. They choke and sputter syrupy spittle, losing d8 VIG.',
    'A lone warty guard, delivering a gift to one of the Knights (see opposite). Its curse manifests when the item is used, which the guard encourages the Knight to do later. The curse lasts an entire Season.',
    'Twelve warty guards ride forward, demanding the Knights visit the Toad. They must swear to him or die.',
  ],
  'The Colossus': [
    'An elderly sculpter toils away, carving a great statue into a cliff face. He boasts that the statue is based on him in his youthful prime. He knows he is dying and longs for immortality.',
    'Across the Realm the earth shakes and rumbles as the Colossus awakes.',
    'A crushed stone house, petty belongings scattered across the nearby field. Looks as if it was bombarded with stones.',
    'The Hammer Knight rides, declaring they are seeking the Colossus, who has been terrorising the area.',
    'Two warbands of a mercenary company fight the Colossus, gradually realising they\'re unable to harm its stone body.',
    'In the distance, the Colossus is leaning against a mountainside. With a groan they collapse into a heap, their form merging with that of the mountain. After a few moments the new rock is covered in red and green moss.',
  ],
  'The Fortress': [
    'The Thorn Seer roams the Realm, proclaiming an invasion of great scuttling monsters is coming soon.',
    'A messenger declares that the Thorn Seer has reclaimed a lost fortress (in the Myth Hex), creating an impenetrable sanctuary for when the invasion comes.',
    'Three claw swarm cutters peer from their tunnels, scouts for the invasion. If seen they scutter back underground.',
    'A smith and her three young apprentices are looking for a new home. They left the Fortress, as the Thorn Seer wanted the impossible from them, demanding whole walls of iron be built.',
    'The voice of the Thorn Seer is heard across the land. The invasion is here, numberless hordes of the claw swarm attacking the Fortress. They will not actually breach the Fortress, as they are creations of the Thorn Seer.',
    'The invasion defeated, the Thorn Seer demands to be made ruler of the Realm, the Fortress as his Seat of Power.',
  ],
  'The Citadel': [
    'The silhouette of the Citadel appears on the horizon, teetering and crooked. Any Seers you meet warn you not to go there.',
    'The nearest Seer skulks between the trees, seeking a new Sanctum so that the Watcher will not find them.',
    'Iron hounds, forged in the Citadel, scour the land, terrorising but not harming Seers. A pack of four charge past the Company, heading to the nearest Seer.',
    'The Watcher from the Citadel is seeking out every Seer, warning them not to interfere with the destiny of the Realm.',
    'A glowing orb falls from the sky, landing with an explosion in the nearby woods. Screams follow from the crash site, and an Immolated Seer bursts from the woods. In their death throes they attack any nearby, losing d6 VIG each round.',
    'The Citadel glows, flooding the Realm with intense white light. Seers scream. When the light fades the Citadel is gone.',
  ],
  'The Catacomb': [
    'Beneath a wilting tree, a heap of misshapen bones, seeming to sprout from the ground itself. They feel slightly warm.',
    'A narrow stone stairway leads down, below a huge blackened tree. It twists into a branching tunnel, each of the three branches concealing a lurking Boneborn. They attack anybody who enters.',
    'A grinding sound beyond the trees. Investigating reveals a rushing river of bones, heading from the Myth Hex, running toward the nearest body of water.',
    'The ground opens, the Company trapped in an arena of bones. They must fight three waves, each of d6 Boneborn. If they survive, a stairway to the surface opens.',
    'Three warbands of Bones at Arms march forward. They roam the land, taking out their anger on the living.',
    'The Bone Slayer emerges, fighting on behalf of all of the dead. He fights any challengers in a duel, banishing losers to a bony underground prison. Turns to ash if defeated, releasing all prisoners.',
  ],
  'The Hound': [
    'A search party. They\'re looking for an elderly woman, a herb gatherer. She\'s been missing for days.',
    'First a patch of blood, then pieces of flesh, gradually becoming clear as the remains of the missing elderly woman.',
    'Another heap of torn remains, this time some sort of deer. All present must pass a CLA Save or else feel compelled to sniff and paw at the remains. They now have the Hound Within (see opposite), the effects lasting until this Myth is resolved.',
    'The shadows seem to grow. Any who brave the darkness are attacked by the Hound in Shadow. It does not attack those affected by the Hound Within unless they attack first.',
    'An icy wind, then the Hound on the Wind attacks from nowhere, focusing its attacks on those affected by the Hound Within. If slain, it returns to the wind.',
    'A heap of flesh and bones. The Hound in Flesh bursts out, fighting to the death.',
  ],
  'The Glade': [
    'A calm glade amid dense trees. Complete silence. Three empty plinths, one each in black, grey, and white stone. Anyone attempting to leave the clearing finds themselves back within it until an offering is left on each plinth, regardless of its value.',
    'In the Glade, the White Stone Hunter asks "whom shall I aid?â€ to whoever left their offering. They vanish and perform a kind act to that person.',
    'In the Glade, the white offering is returned.',
    'In the Glade, the Grey Stone Hunter asks "whom shall I punish?â€ to whoever left their offering. They vanish and perform a punishment, the effects lasting until the next Spring (see opposite).',
    'In the Glade, the grey offering is returned.',
    'In the Glade, the Black Stone Hunter asks "whom shall I kill?â€ to whoever left their offering. They vanish and attempt to kill that person. The offering is left on the body of the target if killed.',
  ],
  'The Tournament': [
    'A tinkerer, accompanied by his Clockwork Knights. He boasts that a tournament will see his Knights defeat any others.',
    'A messenger from the Seat of Power. The Company is called to represent the Realm against the Clockwork Knights.',
    'Nimiod parades his Clockwork Knights before the crowd. The Company are also presented for those watching.',
    'The Company compete all together, paired against a Company of Clockwork Knights. It is a mounted battle, melee weapons only, competitors eliminated if they take a Mortal Wound.',
    'Now the Company must fight on foot, no shields permitted.',
    'Finally, one Knight must take on the Clockwork Champion.',
  ],
  'The Bull': [
    'Leaf-covered acolytes parade a newly born green bull, declaring a blessing on the Realm. They are taking him to a secret location for safekeeping.',
    'People rejoice in the Blessing of the Bull, now clearly taking effect (see opposite).',
    'On a dusty trail, the Bull lies dead. A scream is heard in the distance, two children running to say that they saw the Knights standing over the corpse. The Blessings of the Bull are lost.',
    'Five leaf-clad guards immediately charge the Knights, declaring them enemies of the Realm for killing the Bull.',
    'A pair of winged fiends are seen in the distance, harassing a lost horse, tormenting it with their blades. They flee if confronted.',
    'A lone leaf-clad guard is fending off an attack from five winged fiends, emboldened by their numbers. If the guard survives he vouches for the Knights\' innocence.',
  ],
  'The Hydra': [
    'The Candle Knight lies broken in the road, unable to walk. They tell of the Hydra rising from a pool of stagnant water. It killed the rest of her Company. It cannot be killed. It must be endured.',
    'A wide hole leading down into damp darkness. Any disturbance awakens the Hydra, bursting forth and attacking the Company. It shrugs off any attack.',
    'Atop a hill, the Hydra screeches triumphantly in the ruins of a shattered stone outpost. It fights if disturbed, mocking the Company if they do not realise it cannot be killed.',
    'A rapidly spreading fire among the trees. The Hydra waits in ambush, now able to breathe fire (d8 blast).',
    'A roar from above, and the Hydra descends, now winged and able to fly.',
    'The Hydra, visibly weakened, crawls toward a bubbling spring. As it submerges itself the water boils, turning black, and the Hydra is gone.',
  ],
  'The Spire': [
    'A finely-dressed mushroom gatherer is complaining of a lean harvest. He says a great fungal spire is overdue, which will spread new fungus around the Realm.',
    'A haze of yellow spores on the wind. Those inhaling it see the world around them start to bend and breathe, mouths opening in the ground. It soon passes.',
    'Six fungal serfs are out gathering food to take back to the Spire. They take without asking but have no will to fight.',
    'A round cabin on a wooded hill, shouting within. Two stargazers, sisters, each yelling that the other one is a shape- shifter from the stars. They have both been tricked by hallucinogenic spores.',
    'The Fungal Knight shambles forward, ensuring nobody plans to interfere with the Spire. He has little appetite to fight and just wants to rot away to sludge.',
    'A squelch heard across the Realm. The Spire and all fungal beings collapse into sludge, seeping into the ground. Next season the fungus will be bountiful.',
  ],
  'The Sprite': [
    'A half-asleep fisherman by a duckweed- covered pond. He warns the "old girl o\' the pondâ€ can\'t be trusted on her word.',
    'A pond thick with duckweed, the Sprite emerges, an old woman with the voice and movement of a child. She takes a liking to one member of the Company and asks lots about them before fleeing into the pond.',
    'Another weed-covered pond. The Sprite emerges in the centre, appearing serious. She asks her beloved to name any object they want, from the past, present, or future. She insists until they give an answer, then ducks back under water.',
    'Two beings of greenish water (see opposite) fight loudly, each proclaiming that "she loves only meâ€.',
    'A still lake, the green arms of the Sprite emerging on the bank, holding the requested item for their beloved. She attacks if the gift is refused.',
    'The Sprite, now angry, is here to reclaim the gift. She\'ll take it by force if needed.',
  ],
  'The Hole': [
    'A hole in the ground rips open, growing as trees and rocks tumble in. A small blue Holfolk, Gruff, scurries out into a tree. She is shy, but explains that this only happens when there\'s work to be done on the surface. Those from above can\'t enter the Hole, held back by an invisible force.',
    'Four Holfolk run past, screaming. An angry man on a horse chases them down, claiming they are spies from a wicked Realm. They are just curious, really.',
    'A team of Ardwright builders hammer away at a great project (see opposite). They explain what it is, but not why, and will not indulge in conversation.',
    'Bear-a-boar staggers around the woods, calling out a challenge to any animal that disputes his sovereignty. A pitiful sight.',
    'A band of Holfolk have Bear-a-boar in chains, taking him back to the Hole where he was banished.',
    'A team of Ardwrights are sealing up a hole in the ground, the final entrance to their world, their work completed.',
  ],
  'The Mist': [
    'The air turns cool and a thin mist begins to roll in. A flock of red crows fly past, shrieking as they make urgent flight.',
    'The Mist thickens, a cold leaden curtain. Vision beyond each Hex is impossible.',
    'Six horrors lurk just beyond vision, haunting sounds and faint shadows. They stalk the Company, only striking if somebody becomes isolated.',
    'The Mist grows ever more dense, vision limited to a few feet. Even bright lights fade to a dull glow. All travel is blind.',
    'A militia warband, defected from a nearby Holding, open fire on the Company, mistaking them for horrors in the Mist.',
    'A dull bell clangs, a towering figure barely visible striding through the Mist. It\'s impossible to get closer to it. As it fades into the distance the Mist begins to clear. By the next Morning it has completely passed, leaving silvery dew. A Seer has been taken by the Mist, never to return.',
  ],
  'The Gargoyle': [
    'Two boisterous lads clamber on a ruined temple, smashing the eroded statuary with a heavy hammer. They say they\'re just following orders from a nearby Seer.',
    'The Gargoyle descends on the Company, shouting that he means no harm. He\'s looking for a lost item, and expects the Knights to find it. He will cause an argument for his own amusement if he can, otherwise he leaves.',
    'Atop a huge stone ruin, the Gargoyle carves away at the stone with his bare hands, sculpting beasts. Two such beasts watch on, eager for a new companion.',
    'In the shade of a grey tree the Gargoyle argues with a nearby Seer. He claims that he alone gives the Seers their knowledge. This is a lie.',
    'The two lads who were smashing statues lie petrified by a sculpted beast\'s bite.',
    'In a quarry the Gargoyle smashes his sculpted beasts to rubble one by one. They don\'t resist. After this he takes flight for another Realm, declaring this one dull.',
  ],
  'The Changeling': [
    'A warm gust. A dove looks at one Knight questioningly before fluttering away. Secretly roll or choose a victim (see opposite) whom the Changeling has captured, stealing their form, memories, and place within the Realm.',
    'An elderly rider sits on a wall, his steed chased away by horned wolves. He passes on a Seer\'s warning, the Changeling walks the Realm. Trust no one.',
    'A mature Knight (rolled as normal) arriving in the Realm, seeking the Seat of Power to offer her service. If she is not the Changeling she has good intentions.',
    'A fleshy door in a tree trunk. It snaps shut as quickly as it is noticed, no trace left.',
    'A pair of horned wolves leap from hiding, attacking a random member of the Company, trying to drag them away.',
    'Whoever is the Changeling stands in a clearing, facing away from the Company. If disturbed they unfold into their true form before fleeing, looking for a passage back to their own world.',
  ],
  'The Inferno': [
    'A faint heat can be felt from the soft parts of the ground, like the embers of yesterday\'s fire.',
    'Smoke rises from behind a row of trees. A crackling forest fire burns. It can be stopped if the Company acts quickly, else this small patch of forest burns down.',
    'An orchard lies burned to ash, the young farmer weeps among the embers. They\'re left with no choice but to plead for aid at the nearest Holding.',
    'A smouldering rift in the ground yawns open, the Red Serpent emerging, writhing through the hot air like a great eel. It demands gold and will engage in no other topic of conversation.',
    'A stone watchtower, two guards within, slowly sinking into the ground. The stone appears to be melting as the ground opens up, swallowing the tower in a pit of flame.',
    'The Serpent encircles a pile of riches, taken from all over the Realm, slowly sinking back into the molten earth below.',
  ],
  'The Harp': [
    'The wind rises, rustling branches of nearby trees, almost sounding like music for a moment.',
    'A frail carpenter is rummaging through the woods, grumbling as he searches for just the right type of wood. He says he\'s working on a great project, but is reluctant to share details.',
    'The carpenter cries out, he\'s fighting off six wood centipedes as he tries to carry freshly cut wood back to his workshop.',
    'The wind stirs the branches and leaves, glittering music in the air, now loud enough to hear clearly (see opposite). This affects all in the Realm.',
    'The carpenter, riding a rickety cart, the Harp concealed beneath a grey blanket. He appears fraught, insisting the Knights take the Harp and make sure it doesn\'t fall into the wrong hands.',
    'A parade of white-cloaked acolytes lead a council of Seers from across the Realm. They declare that the Harp must be buried until it is truly needed.',
  ],
  'The Tree': [
    'On the horizon, twisting branches of a great tree, black and blue.',
    'The branches on the horizon seem to grow with each moment, fading to grey, then white, as they reach into the clouds and spread above every part of the Realm.',
    'Branches scrape the clouds in every part of the Realm. With a scratching scream six cloud raiders fall from above, landing unharmed, looking to seize whatever they can carry back to the clouds.',
    'A militia warband march toward the Tree, aiming to chop it down. They do not know that earthly tools cannot harm the Tree.',
    'Great branches fall from the sky across the Realm. One falls nearby, a pair of cloud creatures clinging on before attacking in panic.',
    'With a thunderous creak the Tree begins to lean. A moment later it falls, followed by a rain of branches. The Myth Hex and all adjacent Hexes are devastated, causing 2d12 Damage to all within.',
  ],
  'The Pool': [
    'A joyous farmer skips and sings, leading an ox made entirely of gold. She claims she wished for the ox after drinking from the Pool. Hasn\'t got much of a plan for what to do with the ox.',
    'An elderly man, crying out for help. Claims that a curse has left him old, previously a healthy young hunter.',
    'Beneath a shady canopy, light peeks through, directing attention to the Pool, surrounded by round stones.',
    'Two bodies lie on a large bloodstain, seemingly having stabbed each other. A dried-up pool sits between them.',
    'The Pool presents itself again, this time atop a hill, among jagged rocks.',
    'A babbling sound echoes on the air. The mossy earth yawns and a great stone cauldron rises up. Here the Pool provides enough water for the Company to drink as much as they like, though each receive just one effect. This remains here until the end of the Season.',
  ],
  'The Elephant': [
    'With thunderous steps, the Elephant Knight parades past with armoured soldiers. She marches toward the Seat of Power to receive a hero\'s welcome.',
    'Excited children bicker over which of the Elephant Knight\'s deeds were the greatest (see opposite).',
    'A cruel hunter watches from the shadows, quietly alerting the Company and asking if they have seen the Elephant. He is hunting it for sport.',
    'The Elephant lies dead, the Elephant Knight screaming in anger, running into the distance. The hunter lurks, waiting for a safe moment to claim his trophy.',
    'In a muddy pit, the Elephant Knight slathers herself in wet clay, shouting to the sky in a language you cannot speak. She fights off any attempt to stop her, leaving when completely caked in clay.',
    'A monstrous clay elephant smashes at trees, trumpets at the sky. Heavy rain begins to fall, washing the creature away into the damp earth.',
  ],
  'The Snail': [
    'Over crooked rocks, a trail of slime has left runic inscriptions in the stone. Nobody recognises the language, but everybody can understand it. It promises "the truth in timeâ€.',
    'A narrow, slime-covered passage leads down into the darkness. On the walls within, runes glowing, promising "passage to wherever you wishâ€. The tunnel leads to the desired location with just a Phase of travel, then closes, and five helix beasts launch an ambush.',
    'A huge empty snail shell, like a great cave. Entering shows a taunting vision of the future (see opposite).',
    'A spiral of runes marked on a white cliff, advising "avoid the short cutsâ€.',
    'A thick slime covers the whole Realm. Animals refuse to travel across it.',
    'The Snail approaches. He asks what the Company have learned from his lessons. Takes any answer as proof of his methods and philosophy before gliding toward another Realm, his slime fading away.',
  ],
  'The Cave': [
    'A wide cave mouth looms from a vine- cloaked cliff. It seems empty, but echoes sound slightly altered.',
    'Three iron pilgrims attempt to seal the cave, claiming it can only cause harm.',
    'The Cave, a familiar shape and echo. This time a glow emanates from within, revealing 3 useful crystals (see opposite).',
    'The Cave appears again, on a new cliff face, the word "goldâ€ echos from within. Anybody entering awakens the beast of solid darkness, which only fights to prevent entry to the Cave. Beyond the beast lies a heavy coffer of gold.',
    'The Cave appears on a great boulder, now with eye-like holes and tooth-like stalactites. It slowly speaks, granting one question to each Knight present. It knows all and answers to the best of its ability.',
    'A towering figure strides out of a shadow, like folds of material darkness. He is the Debt Collector, here to take payment for the Cave. He accepts anything of value, and tries to kill those who won\'t pay.',
  ],
  'The Apparatus': [
    'Mother and daughter trappers, searching for ducks. They have noticed a strange order to the Realm recently (see opposite).',
    'A learned numerator and his young scribe note down observations of nature. He claims that the time of order may be here, where the future can be seen in calculations, not the whims of Seers.',
    'A great bridge spanning a ravine. The Brawler Knight sits on a ledge. States that she\'d normally fight those passing over, but doesn\'t see the point anymore.',
    'The numerator\'s scribe rides, blowing a trumpet. They\'re declaring that the Apparatus is complete, and the numerator can calculate the future perfectly. The age of Seers is over!',
    'A warband of Knights, loyal to the Seers, rides toward the Apparatus to destroy it, demanding the Company join them.',
    'The numerator rides on an old steed, pleading for the Company\'s protection. If left unchecked, the Seer-loyal Knights ride ahead and break the Apparatus.',
  ],
  'The Rock': [
    'A breeze with the scent of steel and blood.',
    'A dancing farmer is herding her geese and dragging a skeletal corpse wrapped in cloth. She gladly explains that she\'s taking her grandfather to the Rock, the only resting place for such a warrior.',
    'A Knight of white stone stands guarding a withered tree, just a few pieces of fruit on its branches (see opposite). He explains that this fruit is being kept for warriors returning from the Rock. Punishments for eating the fruit can be lifted by a Seer.',
    'A band of nine pilgrims seek the Rock. They offer protective talismans to Knights. These will ensure that warriors returning from the Rock do not mistake the Knights for enemies of the Realm.',
    'An invigorating storm. With each flash of lightning the sound of battle can be heard.',
    'Mist rolls back from a lake, revealing a rocky island within, a rowboat on the shore. Three bellowing warbands of warriors, waiting in death, ready to serve the Realm in battle one last time.',
  ],
};
